# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e148180ba34f88669def3e63c97fc871fa07771a3f0060c5a51f1e8aab1f2a088cb6f699bf0bb11bd8d5396eb066782562eea76356e0f166f3b7f7f73cab1de

test:
  secret_key_base: fbb7cc9dafb3c5a4eb933b56583437b61aa4f6a1ee1cd98ec58879ce3dd4d11d875f2359127887528e26940bfd91e67420fe5843319e841c8e52a73b86f5f234

# Do not keep production secrets in the repository,
# instead read values from the environment.
