backgrounds:
  homepage: "Hawaiian.jpg"
  article: "Rolling.jpg"

article_stamps: ["lab", "log", "tech", "thought", "other" ,"all"]

# article_type:
#   science: "science"
#   tech: "tech"
#   thought: "thought"
#   log: "log"
