backgrounds:
  homepage: "Hawaiian.jpg"
  article: "Rolling.jpg"
  link: "Cosmos09.jpg"

article_stamps: ["lab", "log", "tech", "thought", "other" ,"all"]

link:
  local_freegeoip: "http://127.0.0.1:8081/json/"

error: -1

geo_greeting:
  prefix0: "Greeting, traveller"
  prefix: "你好, Visitor from"
  prefix1: "别来无恙, Visitor from"
  prefix2: "一日不见, 如隔三秋, Visitor from"

  ip_geo_unknow: "unknow region"
  expire_sec: 256
  unpersice_country: ["China", "CN"]



# article_type:
#   science: "science"
#   tech: "tech"
#   thought: "thought"
#   log: "log"
