backgrounds:
  homepage: "Hawaiian.jpg"
  article: "Rolling.jpg"
  link: "Cosmos09.jpg"

article_stamps: ["lab", "log", "tech", "thought", "other" ,"all"]

link:
  local_freegeoip: "http://127.0.0.1:8081/json/"

error: -1

geo_greeting:
  prefix: "你好, Visitor from"
  ip_geo_unknow: "unknow region"
  expire_sec: 64
  unpersice_country: ["China"]



# article_type:
#   science: "science"
#   tech: "tech"
#   thought: "thought"
#   log: "log"
